import time
import os

def fadeIn():
  f = open('txt-assets/fadeOut/4.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/fadeOut/3.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/fadeOut/2.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/fadeOut/1.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/fadeOut/2.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/fadeOut/3.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/fadeOut/4.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/fadeOut/5.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.2)
  clear = lambda: os.system('clear')
  clear()