import time
import os

def stingIn():
  f = open('txt-assets/transSting/1.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/2.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/3.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/4.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/5.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/6.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/7.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/8.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/9.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
  f = open('txt-assets/transSting/10.txt', 'r')
  lMsg = f.read()
  print (lMsg)
  f.close()
  time.sleep(0.05)
  clear = lambda: os.system('clear')
  clear()
